spring:
  application:
    name: "In Ligte Luim"
#  datasource:
#    url: jdbc:h2:mem:inligteluim
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:
    url: jdbc:postgresql://localhost:5432/inligteluim
    username: postgres
    password: "@Tinus"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

token:
  signing:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "In Ligte Luim API"
    description: "Family Management API with JWT Authentication"
    version: "1.0.0"

# PostgreSQL configuration (commented out for initial setup)
#  datasource:
#    url: jdbc:postgresql://localhost:5432/inligteluim
#    username: postgres
#    password: "@Tinus"